version: '3.8'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - frontend_backend
    
    

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    depends_on:
      - db
    networks:
      - frontend_backend
      - backend_db
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER_FILE: /run/secrets/user
      PGPASSWORD_FILE: /run/secrets/password
      PGDATABASE_FILE: /run/secrets/database  
    read_only: true
    cap_add:
      - NET_ADMIN  
    cap_drop:
      - ALL
    secrets:
      - user
      - password
      - database

  db:
    image: akshay29122003/demorepo1:db
    networks:
      - backend_db
    ports:
      - "5433:5432"
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER_FILE: /run/secrets/user
      PGPASSWORD_FILE: /run/secrets/password
      PGDATABASE_FILE: /run/secrets/database  
    volumes:
      - mydb:/var/lib/postgresql/data  
    secrets:
      - user
      - password
      - database

networks:
  frontend_backend:
    driver: bridge
  backend_db:
    driver: bridge

volumes:
  mydb:

secrets:
  user:
    file: ./user.txt
  password:
    file: ./password.txt
  database:
    file: ./database.txt
