version: '3.8'

services:
  web:
    image: akshay29122003/demorepo1:web
    ports:
      - "8000:80"

  app:
    image: akshay29122003/demorepo1:app
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER_FILE: /run/secrets/pg_user_pass
      PGPASSWORD_FILE: /run/secrets/pg_password_pass
      PGDATABASE_FILE: /run/secrets/pg_database
      PGPORT: 5432
    

  db:
    image: akshay29122003/demorepo1:db
    ports:
      - "5432:5432"
    

secrets:
  pg_database:
    external: true
  pg_user_pass:
    external: true
  pg_password_pass:
    external: true

